#!/usr/bin/env python3

import argparse
from pathlib import Path
import os
import subprocess

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument("files", nargs = '*')
args = arg_parser.parse_args()

home_dir = Path(os.getenv("HOME"))
dots_dir = home_dir / ".dotfiles"

for file in args.files:
    file = Path(file).resolve()
    assert(file.exists())
    relative_path = file.relative_to(home_dir)
    target_path = home_dir / ".dotfiles" / relative_path
    target_path.parent.mkdir(parents=True, exist_ok=True)
    file.rename(dots_dir / relative_path)
    

subprocess.run(["stow", "-d", dots_dir, "."])
